### ISSUE TITLE
Version 4 - Change list

### ISSUE THREAD

**Issue by jameskolce** [ConciseCSS/concise.css#154]
### General Changes

- [x] #149 Add truncate class for table cells
- [x] #152 Add styles for navigation lists
- [x] #153 Add modular scale for typography
- [x] #155 Delete unnecessary styles for figures
- [x] #156 Add variable to allow automatic margins for some block elements
- [x] #159 Use cssnano for the minified version
- [x] #161 Update dependencies
- [x] #164 Move the type scale variables to the globals file
- [x] #166 Replace 'watch' with 'chokidar'
- [x] #168 Port some of the features of Normalize-OpenType.css
- [x] #180 Change default font size and Add $base-font-size equivalent for big displays
- [x] #182 Reduce the size of the buttons

### Breaking Changes
- [x] #150 Separate Concise UI from the core (Now at https://github.com/ConciseCSS/concise-ui)
- [x] #157 Reorganize file structure
- [x] #158 Update normalization styles
- [x] #160 Use custom media queries and media ranges
- [x] #162 Use concise-cli for compilation
- [x] #163 Replace unitSize() with a "lh" custom unit for vertical rhythm
- [x] #165 Increase size of spacing variables 
- [x] #170 Delete custom directory
- [x] #171 Use 'pr' unit instead of pxToEm() and pxToRem()
- [x] #172 Delete clearfix mixin and suggest the use of Flexbox for layouts
- [x] #178 Make the $base-font-size mobile-first and increase its value
- [x] #175 Delete non-responsive functionality
- [x] #176 Use a Flexbox-based grid system
- [x] #181 Delete horizontal definition lists
- [x] #183 Turn on automatic margins by default
